### ISSUE TITLE
API: Módulo de Informaciones

### ISSUE THREAD

**Issue by jjgumucio** [RancaguaInnova/API#60]

**Comment by JEPEREZR** [comment]
- Se agrega nuevas colección  de categorías , que permite registrar las distintas categorías de información y permitir la asociación con la colección de departamentos.
- Se crean los resolver correspondientes para  obtener la información del nuevo colección desde el back-office y desde los webview.
- Se agregan nuevos campos en la colección de departamentos que permiten cargar las imágenes de los iconos y header que se visualizan en el webview.
